### ISSUE TITLE
XS2AiOS Violates the ios naming standard

### ISSUE THREAD

**Issue by dev-at-webid-solutions-dot-de** [FinTecSystems/xs2a-ios#29]
XS2A is not using an iOS naming standard (https://github.com/swiftlang/swift/issues/43510) since the module and the main public class have the same name. So to solve the problem of this dependency, we propose that you distribute it to us embedded within your framework, thus guaranteeing compatibility and avoiding problems like Shadowed Name and the crashes when a xcframework try to use it.

It would be great, if you could deliver a version 2.0.0 of your XS2AiOS, in which the class XS2AiOS and all it usages (other code-references, documentatoin, etc.) was renamed to e.g. XS2A

**Comment by fritzfelix** [comment]
Fixed by https://github.com/FinTecSystems/xs2a-ios/pull/30. Thank you for the PR.
