### ISSUE TITLE
Add setter for language of the overlays in configuration

### ISSUE THREAD

**Issue by TokaMohsen** [FinTecSystems/xs2a-ios#9]
configuration of overlay can have option to set certain language instead of depend on device language

**Comment by fritzfr** [comment]
Hey @TokaMohsen,
this has been fixed in https://github.com/FinTecSystems/xs2a-ios/commit/2cf53d327173aba250d2df54f7238d2c3232cb82 and is now live with 1.7.1.

Cheers
